### PR TITLE
Resource field renames

### LINKED ISSUE #154: Rename `UrlType` to `TransportLayer`
Seems to better encapsulate the purpose of specifying https/ssh/file. "I'm getting my git/hg/file through the https/ssh-protocol/file-system".

### PR DESCRIPTION
**Pull request by Ben-PH**
url: universal resource locator. My thesis is as follows

`git+ssh://foobar?....#....`

`git`: that is the resource type
`ssh`: this is the the scheme used to describe the transport channel
`foobar?...`: this describes the location

Note how git, merc, and file have both location and transport layer. Similar to how the various gitforge variants were flattened into `GitForge` variant, I plan to flatten `Git`, `Mercurial`, `File`, and any other relevant ones into a `ResourceType` (or similarly named) type

will close #154

### CODE REVIEW

**Review by a-kenji — APPROVED** [review]
LGTM, thank you for the reasoning in the PR.
Can you get that into the commits themselves as well? Would appreciate that.

**Comment by Ben-PH** [comment]
"into the commits themselves": as in into the changes made in the PR, or the commit messages? or both?

**Comment by a-kenji** [comment]
I meant into the commit messages of the change.

**Comment by Ben-PH** [comment]
Is that the sort of thing you had in mind?

**Pull request merged**
